<?php /** @var \Magento\Backend\Block\Template $block */ ?>
<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <?php echo $block->getChildHtml() ?>
            <form class="action-element"
                  action="<?php echo $block->escapeUrl($block->getUrl('*/reset/index')) ?>"
                  method="post">
                <input name="form_key"
                       type="hidden"
                       value="<?php echo $block->escapeHtmlAttr($block->getFormKey()) ?>"/>
                <button class="action-primary"
                        type="submit"
                        title="<?php echo $block->escapeHtmlAttr(__('Reset OPcache')) ?>">
                    <?php echo $block->escapeHtml(__('Reset OPcache')) ?>
                </button>
            </form>
        </div>
    </div>
</div>
